# Generated by Django 3.1 on 2020-08-23 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_count', models.IntegerField(default=0)),
                ('process_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('KILLED', 'Killed')], default='RUNNING', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='JobParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('post_code', models.CharField(max_length=15)),
                ('delivery_date', models.DateField()),
                ('collection_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('ERROR', 'Error'), ('RESTART', 'Restart')], default='NEW', max_length=10)),
                ('result', models.TextField(blank=True, null=True)),
                ('job_params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobparams')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.processinfo')),
            ],
        ),
    ]
